kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb-pvc
  namespace: easyshop
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
   - ReadWriteOnce    
  storageClassName: "" 
  volumeName: mongodb-pv   
