apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  rootUsername: {{ .Values.mongodb.auth.rootUsername | b64enc }}
  rootPassword: {{ .Values.mongodb.auth.rootPassword | b64enc }}
  database: {{ .Values.mongodb.auth.database | b64enc }}
